package main

import "kodae/internal/token"

func tokenKindName(t token.Type) string {
	switch t {
	case token.ILLEGAL:
		return "ILLEGAL"
	case token.EOF:
		return "EOF"
	case token.NEWLINE:
		return "NEWLINE"
	case token.IDENT:
		return "IDENT"
	case token.INTLIT:
		return "INTLIT"
	case token.FLOATLIT:
		return "FLOATLIT"
	case token.STRLIT:
		return "STRLIT"
	case token.FN:
		return "fn"
	case token.LET:
		return "let"
	case token.CONST:
		return "const"
	case token.IF:
		return "if"
	case token.ELSE:
		return "else"
	case token.WHILE:
		return "while"
	case token.FOR:
		return "for"
	case token.IN:
		return "in"
	case token.LOOP:
		return "loop"
	case token.BREAK:
		return "break"
	case token.RETURN:
		return "return"
	case token.STRUCT:
		return "struct"
	case token.MODULE:
		return "module"
	case token.USE:
		return "use"
	case token.PUB:
		return "pub"
	case token.EXTERN:
		return "extern"
	case token.TRUE:
		return "true"
	case token.FALSE:
		return "false"
	case token.AS:
		return "as"
	case token.RESULT:
		return "result"
	case token.CATCH:
		return "catch"
	case token.OK:
		return "ok"
	case token.ERR:
		return "err"
	case token.ENUM:
		return "enum"
	case token.MATCH:
		return "match"
	case token.NONE:
		return "none"
	case token.COMMA:
		return "COMMA"
	case token.COLON:
		return "COLON"
	case token.SEMI:
		return "SEMI"
	case token.LPAREN:
		return "LPAREN"
	case token.RPAREN:
		return "RPAREN"
	case token.LBRACE:
		return "LBRACE"
	case token.RBRACE:
		return "RBRACE"
	case token.LBRACK:
		return "LBRACK"
	case token.RBRACK:
		return "RBRACK"
	case token.PLUS:
		return "PLUS"
	case token.MINUS:
		return "MINUS"
	case token.MUL:
		return "MUL"
	case token.DIV:
		return "DIV"
	case token.MOD:
		return "MOD"
	case token.AND:
		return "AND"
	case token.OR:
		return "OR"
	case token.NOT:
		return "NOT"
	case token.ASSIGN:
		return "ASSIGN"
	case token.EQ:
		return "EQ"
	case token.NEQ:
		return "NEQ"
	case token.LT:
		return "LT"
	case token.GT:
		return "GT"
	case token.LEQ:
		return "LEQ"
	case token.GEQ:
		return "GEQ"
	case token.DOT:
		return "DOT"
	case token.DOTDOT:
		return "DOTDOT"
	case token.QUEST:
		return "QUEST"
	case token.HASH:
		return "HASH"
	case token.PLUSEQ:
		return "+="
	case token.MINUSEQ:
		return "-="
	case token.MULEQ:
		return "*="
	case token.DIVEQ:
		return "/="
	case token.MODEQ:
		return "%="
	case token.FATARROW:
		return "=>"
	case token.PLUSPLUS:
		return "++"
	case token.MINUSMINUS:
		return "--"
	case token.ELLIPSIS:
		return "..."
	case token.CONTINUE:
		return "continue"
	case token.DEFER:
		return "defer"
	default:
		return "unknown"
	}
}
