package headergen

import (
	"fmt"
	"strings"

	"kodae/internal/ast"
	"kodae/internal/check"
)

type Options struct {
	LibraryName string
}

func cType(t *check.Type) string {
	if t == nil {
		return "void"
	}
	switch t.Kind {
	case check.KInt, check.KEnum:
		return "int64_t"
	case check.KFloat:
		return "double"
	case check.KBool:
		return "bool"
	case check.KStr:
		return "const char*"
	case check.KStruct:
		return "S_" + t.StructName
	default:
		return "void"
	}
}

func guardName(lib string) string {
	if lib == "" {
		lib = "kodae_lib"
	}
	up := strings.ToUpper(lib)
	up = strings.ReplaceAll(up, "-", "_")
	up = strings.ReplaceAll(up, ".", "_")
	return up + "_H"
}

func Generate(p *ast.Program, inf *check.Info, opt Options) (string, error) {
	var b strings.Builder
	g := guardName(opt.LibraryName)
	fmt.Fprintf(&b, "/* Generated by Kodae */\n#ifndef %s\n#define %s\n\n", g, g)
	b.WriteString("#include <stdint.h>\n#include <stdbool.h>\n\n")

	for _, d := range p.Decls {
		sd, ok := d.(*ast.StructDecl)
		if !ok {
			continue
		}
		st := inf.Struct[sd.Name]
		if st == nil {
			continue
		}
		fmt.Fprintf(&b, "typedef struct S_%s {\n", sd.Name)
		for _, fn := range st.Order {
			fmt.Fprintf(&b, "  %s %s;\n", cType(st.Fields[fn]), fn)
		}
		fmt.Fprintf(&b, "} S_%s;\n\n", sd.Name)
	}

	for _, d := range p.Decls {
		fd, ok := d.(*ast.FnDecl)
		if !ok {
			continue
		}
		var rt *check.Type
		var err error
		if fd.Return == nil {
			rt = check.TpVoid
		} else {
			rt, err = resolveTypeFromInfo(fd.Return, inf)
			if err != nil {
				continue
			}
		}
		if !isCCompatible(rt) {
			continue
		}
		skipFn := false
		for _, p := range fd.Params {
			pt, err := resolveTypeFromInfo(p.T, inf)
			if err != nil || !isCCompatible(pt) {
				skipFn = true
				break
			}
		}
		if skipFn {
			continue
		}
		fmt.Fprintf(&b, "%s %s(", cType(rt), fd.Name)
		for i, p := range fd.Params {
			if i > 0 {
				b.WriteString(", ")
			}
			pt, _ := resolveTypeFromInfo(p.T, inf)
			fmt.Fprintf(&b, "%s %s", cType(pt), p.Name)
		}
		b.WriteString(");\n")
	}

	fmt.Fprintf(&b, "\n#endif /* %s */\n", g)
	return b.String(), nil
}

func resolveTypeFromInfo(tx *ast.TypeExpr, inf *check.Info) (*check.Type, error) {
	if tx == nil {
		return check.TpVoid, nil
	}
	if tx.PtrInner != nil {
		inner, err := resolveTypeFromInfo(tx.PtrInner, inf)
		if err != nil {
			return nil, err
		}
		return &check.Type{Kind: check.KPtr, Pointee: inner}, nil
	}
	if tx.ListInner != nil {
		inner, err := resolveTypeFromInfo(tx.ListInner, inf)
		if err != nil {
			return nil, err
		}
		return &check.Type{Kind: check.KList, Elem: inner}, nil
	}
	if tx.Name == "int" {
		return check.TpInt, nil
	}
	if tx.Name == "float" {
		return check.TpFloat, nil
	}
	if tx.Name == "bool" {
		return check.TpBool, nil
	}
	if tx.Name == "str" {
		return check.TpStr, nil
	}
	if tx.Name == "void" {
		return check.TpVoid, nil
	}
	if st, ok := inf.Struct[tx.Name]; ok {
		return check.StructType(st), nil
	}
	if en, ok := inf.Enums[tx.Name]; ok {
		return &check.Type{Kind: check.KEnum, EnumName: en.Name, EnumRef: en}, nil
	}
	return nil, fmt.Errorf("unknown headergen type %q", tx.Name)
}

func isCCompatible(t *check.Type) bool {
	if t == nil {
		return true
	}
	switch t.Kind {
	case check.KInt, check.KFloat, check.KBool, check.KStr, check.KVoid, check.KEnum, check.KStruct:
		return true
	default:
		return false
	}
}
