// Package llir emits textual LLVM IR for experimental builds.
// Full lowering from ast.* is future work; today we emit a tiny valid module so
// `clang -x ir` can produce an executable (used by `kodae build --backend=llvm`).
package llir

import "fmt"

// EmitMinimalMain returns LLVM IR with @main returning exitCode (i32).
func EmitMinimalMain(exitCode int32) string {
	return fmt.Sprintf(`; generated by kodae llir (experimental)
define i32 @main() #0 {
entry:
  ret i32 %d
}
attributes #0 = { nounwind }
`, exitCode)
}
